### ISSUE TITLE
Flatzinc Segfault

### ISSUE THREAD

**Issue by skosch** [google/or-tools#115]
Should be reproducible with the mzn/fzn files here: https://gist.github.com/skosch/0c7033bdb4171ba76a37

Valgrind says there is something amiss in the presolver:
```
==9922== Process terminating with default action of signal 11 (SIGSEGV)
==9922==  Access not within mapped region at address 0x0
==9922==    at 0x4469B0: operations_research::(anonymous namespace)::Regroup(operations_research::FzConstraint*, std::vector<operations_research::FzIntegerVariable*, std::allocator<operations_research::FzIntegerVariable*> > const&, std::vector<operations_research::FzIntegerVariable*, std::allocator<operations_research::FzIntegerVariable*> > const&)
```

Thanks!

**Comment by lperron** [comment]
I fixed it.

Thanks for the report.

**Comment by skosch** [comment]
Thanks Laurent, but it's not quite fixed yet :( I'm afraid you may have to apply those `empty` checks throughout the entire presolver.

Here's another one that causes a crash in the `PresolveInequalities` function: https://gist.github.com/skosch/e6683b0eaa5351926f2f ... it's got plenty of lines à la `constraint int_le(0, 0)` or `constraint int_max(0, X, Y)`

**Comment by lperron** [comment]
I fixed the second example.
When I have time, I will scan my presolve rules.

**Comment by skosch** [comment]
Thank you! :)
