### ISSUE TITLE
CP-SAT Solver: Check failed

### ISSUE THREAD

**Issue by marbuttner** [google/or-tools#1389]
I've modeled a flexible job shop like problem with tools using CP-SAT. For each tool I have a specific amount available and I use a cumulative constraint to assure that there are no more tools used than available. However, the CP-SAT solver crashes with the error

    Check failed: constraint_to_vars.size() == working_model->constraints_size() (3382 vs. 3383) 
    *** Check failure stack trace: ***
        @        0x1034aab5d  google::LogMessage::Fail()
        @        0x1034a853e  google::LogMessage::SendToLog()
        @        0x1034a953f  google::LogMessage::Flush()
        @        0x1034b3039  google::LogMessageFatal::~LogMessageFatal()
        @        0x1034ab0d5  google::LogMessageFatal::~LogMessageFatal()
        @        0x1044ef0ba  operations_research::sat::PresolveContext::UpdateConstraintVariableUsage()
        @        0x1044fa9b6  operations_research::sat::(anonymous namespace)::PresolveToFixPoint()
        @        0x1044f19bf  operations_research::sat::PresolveCpModel()
        @        0x10453619c  operations_research::sat::(anonymous namespace)::SolveCpModelWithLNS()::$_8::operator()()
        @        0x10452ef16  operations_research::sat::(anonymous namespace)::SolveCpModelWithLNS()
        @        0x104534768  std::__1::__function::__func<>::operator()()
        @        0x104356626  operations_research::RunWorker()
        @        0x104356f9c  std::__1::__thread_proxy<>()
        @     0x7fff582c52eb  _pthread_body
        @     0x7fff582c8249  _pthread_start
    Abort trap: 6

I've attached the [proto file](https://github.com/google/or-tools/files/3349103/cp_proto.tar.gz) with the model.

**Comment by lperron** [comment]
Fixed on master.

You can build from source using the master branch or wait for 7.2 (in the next 2 weeks).

Thanks for the report.

**Comment by marbuttner** [comment]
Sadly, I still get the same error. I've built the source about an hour ago

    Check failed: constraint_to_vars.size() == working_model->constraints_size() (3461 vs. 3462) 
    *** Check failure stack trace: ***
        @        0x106f6593d  google::LogMessage::Fail()
        @        0x106f642e0  google::LogMessage::SendToLog()
        @        0x106f64eff  google::LogMessage::Flush()
        @        0x106f69c69  google::LogMessageFatal::~LogMessageFatal()
        @        0x106f65fa5  google::LogMessageFatal::~LogMessageFatal()
        @        0x1080ec2fa  operations_research::sat::PresolveContext::UpdateConstraintVariableUsage()
        @        0x108113d07  operations_research::sat::CpModelPresolver::PresolveToFixPoint()
        @        0x108114a8c  operations_research::sat::CpModelPresolver::Presolve()
        @        0x108114a22  operations_research::sat::PresolveCpModel()
        @        0x108137f8d  _ZNSt3__110__function6__funcIZN19operations_research3sat12_GLOBAL__N_19LnsSolver12GenerateTaskExEUlvE_NS_9allocatorIS6_EEFvvEEclEv
        @        0x10822cc89  std::__1::__function::__func<>::operator()()
        @        0x107f459b6  operations_research::RunWorker()
        @        0x107f465bc  std::__1::__thread_proxy<>()
        @     0x7fff582c52eb  _pthread_body
        @     0x7fff582c8249  _pthread_start
    Abort trap: 6

It's the same proto file I've attached in my previous comment. Also, I'm setting `num_search_workers` to 8.

**Comment by lperron** [comment]
Are you sure you are on master ?
This is not the default branch.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 2 juil. 2019 à 12:32, marbuttner <notifications@github.com> a
écrit :

**Comment by marbuttner** [comment]
Yes, `git status` prints `On branch master`.

**Comment by lperron** [comment]
git branch master does not change the branch. You need a git reset.

A good indicator is if ortools/sat/subsolver.h is defined or not. It is
only present in the last commits on master.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 2 juil. 2019 à 12:58, marbuttner <notifications@github.com> a
écrit :

**Comment by marbuttner** [comment]
Sorry, I think you misunderstood. I am on branch master and file subsolver.h is there:

    $ md5 ortools/sat/subsolver.h
    MD5 (ortools/sat/subsolver.h) = fd7843db89e612986955e88dabd3613e

**Comment by lperron** [comment]
OK. I just ran your example multiple times, and it was fine.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 2 juil. 2019 à 13:06, marbuttner <notifications@github.com> a
écrit :

**Comment by marbuttner** [comment]
Well, I still don't know what I'm doing wrong. I did a completely fresh build and installed to a new virtual environment. I'm still getting this error.

I'm using the Python API to create and solve the model. I get this error on every run, so it probably is something specific to this model (since other variations run fine). I'm on macOS 10.14.5 if this matters at all.

**Comment by marbuttner** [comment]
The solver still crashes with version 7.2, but only if I set num_search_workers to more than 6; for num_search_workers <= 6 it returns an optimal solution.

    Check failed: constraint_to_vars.size() == working_model->constraints_size() (211 vs. 212) 
    *** Check failure stack trace: ***
        @        0x105f4794d  google::LogMessage::Fail()
        @        0x105f462f0  google::LogMessage::SendToLog()
        @        0x105f46f0f  google::LogMessage::Flush()
        @        0x105f4bc79  google::LogMessageFatal::~LogMessageFatal()
        @        0x105f47fb5  google::LogMessageFatal::~LogMessageFatal()
        @        0x1070ced0a  operations_research::sat::PresolveContext::UpdateConstraintVariableUsage()
        @        0x1070f6717  operations_research::sat::CpModelPresolver::PresolveToFixPoint()
        @        0x1070f749c  operations_research::sat::CpModelPresolver::Presolve()
        @        0x1070f7432  operations_research::sat::PresolveCpModel()
        @        0x10711a352  _ZNSt3__110__function6__funcIZN19operations_research3sat12_GLOBAL__N_19LnsSolver12GenerateTaskExEUlvE_NS_9allocatorIS6_EEFvvEEclEv
        @        0x10720fc29  std::__1::__function::__func<>::operator()()
        @        0x106f28356  operations_research::RunWorker()
        @        0x106f28f5c  std::__1::__thread_proxy<>()
        @     0x7fff7ccc02eb  _pthread_body
        @     0x7fff7ccc3249  _pthread_start
    Abort trap: 6

[The proto file](https://github.com/google/or-tools/files/3391988/cp_proto.tar.gz)

**Comment by lperron** [comment]
Yes. It should be fixed on master.

Can you send me the proto for testing?

Le lun. 15 juil. 2019 à 04:19, marbuttner <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
I ran the attached proto on my laptop (using the master branch).

Ran fine with 8 threads

status: OPTIMAL

objective: 272040

best_bound: 272040

booleans: 55870

conflicts: 37020

branches: 41203

propagations: 342554587

integer_propagations: 373598

walltime: 69.7791

usertime: 69.7791

deterministic_time: 41.1577
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by marbuttner** [comment]
Yes, it works fine now.
