### ISSUE TITLE
Feature request: Generic slack/violation bool variable in sat.cp_model

### ISSUE THREAD

**Issue by PMLP-novo** [google/or-tools#1645]
I really miss a generic slack/violation boolean for constraints that works the following way
`{statement == True} <=> slack==False `
I imaging this as one of the arguments for `cp_model.ConstraintProto`
If I had these I could make a slack for a constraint like this:
`model.Add(x + 2 * y == 5).AddSlack(b.Not())`
And i could make partial constraints that could be used to build very complex constraints

```
def partial(constraint_func, *args,**kwargs):
    # Returns a boolean variable reflecting the truthfullness of the initialized constraint
    slack_bool=constraint_func(*args,**kwargs).MakeSlack()
    return slack_bool.Not()

model.Add(a*3==b).OnlyEnforceIf(partial(model.Add,c==d))
```

As well as writing efficient boolean operations:

```
def AddBoolAllConstraint(litterals, target):
    ct = cp_model.Constraint(self.__model.constraints)
    model_ct = self.__model.constraints[ct.Index()]
    model_ct.bool_and.literals.extend([self.GetOrMakeBooleanIndex(x) for x in literals])
    model_ct.bool_slack.literals.append(target)
    return ct

def AddBoolAndConstraint(a,b,target):
    ct = self.model.AddBoolAllConstraint([a,b],target)
    return ct
```

Compared to the existing `enforcement_literal` it only works one way, so this offers new functionality. In my mind. But I might have overlooked existing functionality.

**Comment by lperron** [comment]
I do not understand your request. 

    model.Add(x + 2 * y == 5).AddSlack(b.Not())

You can write that already.

    model.Add(x + 2 * y == 5).OnlyEnforceIf(b)
    model.Add(x + 2 * y != 5).OnlyEnforceIf(b.Not())

What I can tell you is that I will not add support for anything else that Boolean literals in the OnlyEnforceIf() part.
I will also not add API to measure violations of constraints as the definition is not unique, and can be done easily for a given application (for the simple constraints).

**Comment by PMLP-novo** [comment]
First of all you you can make it with a double `OnlyEnforceIf` for the `Add` method, but can you do that for all constraints? And is that efficient making two of the same constraint to make a two way inferrence? I don't know.

I don't want to change anything of the only enforce if. The idea was that `partial` did output a bool representing the constraints truefullness. Such that constraints can be combined more easily.  I have editet the original partial function. I though this feature could be very nice to give a functional feel for the appilication in general. 

The API request is not to _measure_ the violation, since a constraint is not violated if `slack==True` given the definition of slack. 

My original motivation for this came when i wanted the simple constraint: `a^b <=> c` in one constraints for boolean variables efficiently. And the only thing I came up with where `min(a,b)=c` I would be qurious to how you would make such a constraint?

**Comment by lperron** [comment]
1) my point exactly. We do not support OnlyEnforceIf for most of the
constraints (only bool_or, bool_and, and linear). From this, I do not know
how to support generic partial() methods.
2) I still do not see the difference between your proposal and
OnlyEnforceIf, or tweaking the model.
3) what is the semantic of a^b <=> c ?
if it is x == a and b, this is easy to code:

model.AddBoolOr([a.Not(), b.Not(), c])
model.AddBoolAnd([a, b]).OnlyEnforceIf(c)

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by PMLP-novo** [comment]
1) Sorry when surgesting the partial function I meant outputting a boolean variable not outputting a bool. My mistake and understandably you did not understand what was insight my mind :), corrected in the original implimentation. So the output of the partial function can be used all cases where you can use a boolean variable, since it outputs a boolean variable. And therefore it would work.

2) You are correct that the slack variable can be implimented as:
`
model.[add constraint].OnlyEnforceIf(b)
model.[add negated constraint].OnlyEnforceIf(b.Not())
`
But to my knowledge you have no way of creating a negated constraint for a constraint in general such that  `a_neg.violated==True<=>a.violated==False`  in the existing application. Correct me if I'm wrong. Otherwise I can't see the feature being supported by the existing application. 

3) Thanks for the help it did not solve the original puzzle to make it efficiently in _one_ constraint.  My point is that by having this functionality you would be able to write many more constraints as one constraint and not a combination of constraints.

**Comment by lperron** [comment]
2) negating a constraint is hard in general. I still do not understand
' a_neg.violated==True<=>a.violated==False'.
What is a ?
3) What is the point in writing everything as one constraint ? I do not
like APIs that create constraints silently.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00
