### ISSUE TITLE
routing.WriteAssignment() and back routing.ReadAssignment() fail

### ISSUE THREAD

**Issue by Stepka** [google/or-tools#2069]
Version: 7.5.7466
Language: Python

I use Routing Solver

Operating system: Windows 10

In my case model have found a solution and I tried to save and load it by:
```
    res = routing.WriteAssignment("solution.txt")
    print(res)
    res = routing.ReadAssignment("solution.txt")
    print(res)
```
Saving solution is ok, but for read I see the following error: 
`I0612 15:48:53.935014  4380 assignment.cc:495] No assignment found in solution.sol`

Seems that it is with my case, because a simple test with example from ortools docs save and load solution successfully. 

But why in my case error is occued? In attach saved solution, could you see what the problem can be with the saved solution? 
[solution.txt](https://github.com/google/or-tools/files/4771182/solution.txt)

**Comment by Mizux** [comment]
Please ask on the mailing-list, also try to update your ortools version to see if it's fixed in the latest release

**Comment by Orbifold** [comment]
This ain't fixed I think (we are 2023). A basic write and read is still failing. The documentation is also very sparse on this.
