### ISSUE TITLE
Option to build without SCIP with Makefile

### ISSUE THREAD

**Issue by ankane** [google/or-tools#2134]
**What language and solver does this apply to?**
C++

**Describe the problem you are trying to solve.**

Hi, it looks like SCIP was added in the latest release, which doesn't have an open source license. It'd be nice if there was a way to build OR-Tools without it.

**Describe the solution you'd like**

`USE_SCIP` or similar option for `Makefile` build, since CMake is still considered experimental.

**Describe alternatives you've considered**

Use experimental CMake build instead.

**Comment by lperron** [comment]
Why is that a problem ?

**Comment by ankane** [comment]
I'd like to add OR-Tools to Homebrew, so Mac users can do `brew install or-tools`, but Homebrew requires software to have an open source (OSI-approved) license.

More generally, I think it's nice for users to be able to build OR-Tools without having to worry about non-open source being included. It looks like others have this same concern, fwiw: https://github.com/google/or-tools/issues/2129

**Comment by lperron** [comment]
OK, We will do that asap.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 11 août 2020 à 10:57, Andrew Kane <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Fixed for `make` based builds on master.

**Comment by lperron** [comment]
Side comment, do you need help adding or-tools to homebrew ? This is one of or-tools missing delivery channel. Do you have a description of what you want to include ?

**Comment by ankane** [comment]
Thanks for adding a flag and offering to help! I have working formula here: https://github.com/ankane/homebrew-core/blob/or-tools/Formula/or-tools.rb

I submitted CBC to Homebrew earlier today, so once that's merged and a new release of OR-Tools is out, we should be good to go. I'll test the new flag in a bit to confirm everything works.

**Comment by ankane** [comment]
Just tried with master and it's failing with `cp: dependencies/sources/scip-7.0.1/src/lpi/lpi_glop.cpp: No such file or directory`.

Full logs: https://github.com/ankane/homebrew-core/runs/971549010?check_suite_focus=true

**Comment by lperron** [comment]
You must add BUILD_SCIP=OFF manually in Makefile.local before make
third_party, or pass it to make

option a:
checkout
make Makefile.local
echo BUILD_SCIP=OFF >> Makefile.local
make third_party
make all

option b:
make BUILD_SCIP=OFF third_party all
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 11 août 2020 à 16:20, Andrew Kane <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
I read your log.

1) I pushed the fix for the makefile.

2) I believe you do not need to run make third_party if every dependency is
compiled before.
You will need to generate Makefile.local (make Makefile.local).
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by ankane** [comment]
I tried the latest master without `make third_party` (and `USE_SCIP=OFF`), but it fails with:

```txt
makefiles/Makefile.third_party.unix.mk:46: *** Third party SCIP files was not found! did you run 'make third_party' or set UNIX_SCIP_DIR ?.  Stop.
```

Full logs: https://github.com/ankane/homebrew-core/runs/972227456?check_suite_focus=true

**Comment by lperron** [comment]
Oh sh*t

Le mar. 11 août 2020 à 19:04, Andrew Kane <notifications@github.com> a
écrit :

**Comment by lperron** [comment]
Fixed,

thanks
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
FYI i fixed for windows too ;)

**Comment by ankane** [comment]
Still no luck - same error (with same situation) as https://github.com/google/or-tools/issues/2134#issuecomment-672097603

Full logs: https://github.com/ankane/homebrew-core/runs/973737877?check_suite_focus=true

**Comment by Mizux** [comment]
Few thinks (in any order):
* Currently the variable is called `BUILD_SCIP` **BUT** i'll rename it as `USE_SCIP` to follow the CMake naming convention
-> I'll let you know on this thread once done
* FYI I have created  a formula long time ago https://github.com/Mizux/homebrew-or-tools/blob/master/or-tools.rb
* Homebrew already provide a "full" coin-or-tools/coinor/cbc (using the monolithic svn archive IIRC) so you don't need your custom cbc, cgl, clp, osi and coinutils custom formulae (unless this formula is broken ?).

**Comment by Mizux** [comment]
just renamed it, `USE_SCIP` if you want to test...

**Comment by ankane** [comment]
Thanks @Mizux, missed that it had a different name. It currently builds but `make install` fails (don't mind the 0.0.0 version):

```txt
cp -R dependencies/install/include/scip "/usr/local/Cellar/or-tools/0.0.0/include"
cp: dependencies/install/include/scip: No such file or directory
mkdir "/usr/local/Cellar/or-tools/0.0.0/include/ortools"
make: *** [install_third_party] Error 1
make: *** Waiting for unfinished jobs....
```

Re Homebrew: All dependencies must be in the official repo. The cbc formula was just merged, so no blockers there.

**Comment by Mizux** [comment]
install rule seems broken... on my way to fix them

**Comment by ankane** [comment]
Hey @Mizux, the latest commit seemed to fix it. I'll submit to Homebrew whenever a new version is out.

**Comment by Mizux** [comment]
@ankane just FYI now or-tools depends on C++17 revision so we have to use abseil-cpp build using C++17 (yes abseil-cpp change according to the C++ revision used).

Unfortunately, as expected, homebrew/homebrew-core only provide abseil-cpp in.... C++11 -> ortools.rb is no longer compiling against the "homebrew ecosystem"
see: https://github.com/Mizux/homebrew-or-tools/runs/1031099691?check_suite_focus=true

**Comment by ankane** [comment]
Does that just mean we need to wait until the next abseil LTS version is out?

**Comment by Mizux** [comment]
It means we need to have an `abseil` package compiled against c++17.

I've just sent a bottle to the homebrew community -> https://discourse.brew.sh/t/abseil-and-c-revision/8641

**Comment by ankane** [comment]
It doesn't look like any formula currently depend on it (just search for `abseil` in https://github.com/homebrew/homebrew-core), so should be fine to make the change.

**Comment by Mizux** [comment]
start to have something working: https://github.com/Mizux/homebrew-or-tools/runs/1035669937?check_suite_focus=true
Next step:
- [ ] Send PR to homebrew-core to modify abseil.rb using [my version](https://github.com/Mizux/homebrew-or-tools/blob/master/abseil.rb) 
- [ ] Send PR to homebrew-core to integrate [ortools.rb](https://github.com/Mizux/homebrew-or-tools/blob/master/or-tools.rb) (CMake based build) once release v8.0 is out...

**Comment by ankane** [comment]
Hey @Mizux, was able to get v8.0 working with the following changes: https://github.com/Homebrew/homebrew-core/compare/master...ankane:or-tools3. Let me know if you'd like me to submit, or you'd like to do it.

**Comment by Mizux** [comment]
@ankane well I was waiting to release v8.0 to propose my homebrew package ;)

our ortools.rb and mine differ a little bit (e.g. you don't provide head, you are using archive, i'm using git), i'll try to send you comment then if you want to provide your version, I'm ok (i.e. don't care if you or me send the PR  to homebrew community, I just want to have it integrated inside homebrew-core)

FYI: I already ask on homebrew forum if it will be ok to bump abseil to C++17, it should be ok since no one is using it yet (brew reverse dependencies show nothing)

**Comment by ankane** [comment]
Homebrew prefers the tar.gz url over git whenever possible. Just added the `head` url (I wasn't sure if Homebrew allows this in new formula, but it doesn't generate a warning with the new formula audit). Anyways, feel free to run with your version / steal from this if there are other changes you want to make.

**Comment by Mizux** [comment]
@ankane few bad news:
* adding revision to abseil.rb will break the build
```sh
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
Error: Testing requires the latest version of abseil
Error: Process completed with exit code 1.
```
see: https://github.com/or-tools/homebrew_or-tools/actions/runs/303942900

* greping abseil, it seems `grpc` make it through homebrew-core using c++11 version...
note: in my action a try find reverse deps
```
Run brew uses --recursive --include-build --include-test abseil
  brew uses --recursive --include-build --include-test abseil
  shell: /bin/bash -e {0}
  env:
    VERSION: --HEAD
apache-arrow // depends on grpc
apache-arrow-glib
dvc
grpc // depends directly on abseil
```
see: https://github.com/or-tools/homebrew_or-tools/runs/1246430593?check_suite_focus=true#step:5:1

Side note
* Your or-tools.rb do not provide a .pc which can be cool for auto-tool users and few others tools (ed even cmake has a module to read them...)
see: https://github.com/Homebrew/homebrew-core/compare/master...Mizux:ortools

* you are missing `-DBUILD_SAMPLE=OFF` IIRC

**Comment by ankane** [comment]
Looks like it was accepted 🎉 Thanks @Mizux!
