### ISSUE TITLE
Empty CpSolverResponse in LogSearchProgress

### ISSUE THREAD

**Issue by prissky** [google/or-tools#2189]
**What version of OR-tools and what language are you using?**
Version: v7.8
Language: Java

**Which solver are you using?**
CP-SAT

**What operating system and version?**
Windows 10

**What did you do?**
1. Loaded [unknown-infeasible.zip](https://github.com/google/or-tools/files/5339461/unknown-infeasible.zip)
2. Set LogSearchProgress(true)
3. Solved with SolutionCallback
4. Saw empty CpSolverResponse:

> *** starting Search at 73.05s with 8 workers and subsolvers: [ auto, lp_br, pseudo_cost, no_lp, max_lp, core, feasibility_pump, rnd_lns_auto, var_lns_auto, cst_lns_auto, scheduling_time_window_lns_auto, scheduling_random_lns_auto, rins_lns_auto, rens_lns_auto ]
> #Bound  80.50s best:inf   next:[0,249000] init
> #Done   82.87s  core
> CpSolverResponse:
> status: UNKNOWN
> objective: 0
> best_bound: 0
> booleans: 0
> conflicts: 0
> branches: 0
> propagations: 0
> integer_propagations: 0
> walltime: 0
> usertime: 0
> deterministic_time: 0
> primal_integral: 0

5.  Called System.out.println(cpSolver.responseStats()); and got:

> CpSolverResponse:
> status: INFEASIBLE
> objective: NA
> best_bound: NA
> booleans: 207687
> conflicts: 1409
> branches: 56362
> propagations: 11098615
> integer_propagations: 5488186
> walltime: 87.028
> usertime: 87.028
> deterministic_time: 51.7466
> primal_integral: 0

**What did you expect to see?**
The same stats in logSearchProgress.

**What did you see instead?**
Both _status: UNKNOWN_ and _status: INFEASIBLE_.

**Comment by Mizux** [comment]
IIRC there is a race cond between solution callback workers and solver response
maybe laurent will have more info...

**Comment by lperron** [comment]
Yes. There is a race.  The returned reponse is always right.

**Comment by gregy4** [comment]
I reproduced it also in c++ so it has probably nothing to do with java or swig.

**Comment by lperron** [comment]
Do you have a small code that exhibits it ?

**Comment by gregy4** [comment]
Sorry I don't have it, I executed given proto file in c++. But I know how was proto file created in java so I can try to create some subset of given problem in c++ if it can help you.

**Comment by lperron** [comment]
Is this easy to reproduce ? I have run this proto tens of time on our code, and it never happens.

**Comment by lperron** [comment]
Ok, I cannot reproduce it on the master branch. Thus I am closing the bug.
Thanks for the report, and please reopen if it still happens in 8.0

**Comment by gregy4** [comment]
I can reproduce it on master branch from Saturday, build on current master branch doesn't work in visual studio due to update of absl library.

I can reproduce it in every run on windows, it seems that the problem is not present in linux.

Did you try it on windows ?  You didn't answer my question about smaller example.

**Comment by Mizux** [comment]
> current master branch doesn't work in visual studio due to update of absl library

I guess, it is fixed, otherwise, don't hesitate to open an issue ! Thx

**Comment by gregy4** [comment]
No, it is not fixed. To be sure I tried to build master branch not only with VS (sometimes randomly reports nonexisting errors) but also with clion that seems much better but now with same error with application of patch absl-populate.

**Comment by lperron** [comment]
I just pushed the fix.
A compiler bug.
