### ISSUE TITLE
Constraint Solver random stategies always use seed = 0

### ISSUE THREAD

**Issue by gb96** [google/or-tools#291]
The IntVarStrategy [CHOOSE_RANDOM](https://github.com/google/or-tools/blob/master/src/constraint_solver/constraint_solver.h#L286)  and IntValueStrategy [ASSIGN_RANDOM_VALUE](https://github.com/google/or-tools/blob/master/src/constraint_solver/constraint_solver.h#L368)
currently always result in exactly the same searches because the random number generator is always seeded with the same seed, i.e. 
[ACMRandom::DeterministicSeed()](https://github.com/google/or-tools/blob/master/src/base/random.cc#L106) 

I had a look at setting PhaseParameters to use a better seed, but could not figure out any way to get ConstraintSolver to use a different seed.  If there is a way, it needs to be documented.

[constraint_solver.Reseed](https://github.com/google/or-tools/blob/master/src/constraint_solver/constraint_solver.h#L2844) looks like it should allow a new seed to be specified but the results were still the same deterministic search.

Perhaps the simplest fix would be for ConstraintSolver to seed by default using [ACMRandom::HostnamePidTimeSeed()](https://github.com/google/or-tools/blob/master/src/base/random.cc#L72) instead of [ACMRandom::DeterministicSeed()](https://github.com/google/or-tools/blob/master/src/base/random.cc#L106) ?
DeterministicSeed is probably only useful for testing and debugging.  Most users will want some randomness when they choose the RANDOM strategies.

In my case, since the solver appears to only use one CPU core, I like to execute a separate instance across multiple cores.  However if all solvers are deterministic, they all perform the exact same search and there is no performance gain.

**Comment by furnon** [comment]
When you call Reseed(), do you pass  ACMRandom::HostnamePidTimeSeed() as
argument ? What platform are you using ?

**Comment by gb96** [comment]
Looks like Solver.ReSeed () is actually working.  I was calling it from
python with os.getpid () * time.clock () but for some reason time.clock ()
was always == 0, so I was seeding with 0 producing the default
deterministic behaviour.

When I call Solver.ReSeed (os.getpid ()) more random searches are observed.

**Comment by Grovespaz** [comment]
Does that mean this is solved?

**Comment by gb96** [comment]
I feel like having to call Reseed is a workaround. Random strategies should
by default be random, not so deterministic.

**Comment by sebastianfast** [comment]
Has this issue been worked on so far? Today I discovered that when setting

    db = solver.Phase(variables, solver.CHOOSE_RANDOM, solver.ASSIGN_RANDOM_VALUE)

the results are still the same - not calling solver.ReSeed().

**Comment by lperron** [comment]
Yes, you need to reseed if you want different search. This way, you can debug on particular problem.
