### ISSUE TITLE
Broken link to Google C++ coding style on homepage

### ISSUE THREAD

**Issue by Grovespaz** [google/or-tools#306]
On https://developers.google.com/optimization/ the link to the Google C++ coding style is broken (should it be https://google.github.io/styleguide/cppguide.html ?)

**Comment by paultrow** [comment]
Thanks very much for pointing this out. I have fixed the link.

**Comment by Grovespaz** [comment]
Unfortunately it is still broken on my end, even after refreshing.
