### ISSUE TITLE
Errors when running flatzinc command using the ortools.msc file from the MiniZinc IDE

### ISSUE THREAD

**Issue by zayenz** [google/or-tools#3333]
**What version of OR-Tools and what language are you using?**
Version: main and 9.3.10470
Language: FlatZinc

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**

**What operating system (Linux, Windows, ...) and version?**
MacOS 12.3.1 on M1 Max

**What did you do?**
1. Download and install the FlatZinc distribution of or-tools (or build and package from main)
2. Install the solver into the latest MiniZinc IDE (currently 2.6.3) by adding the directory with the ortools.msc file as a solver search path in the MiniZinc IDE preferences.
4. Solve any model (for example the simplest with just `solve satisfy;`)

**What did you expect to see**

A solved model

**What did you see instead?**
```
=== ERROR ===
```

There where three different things that I needed to fix to get it running
* Comment out the two `warm_start` definitions at the end of the `redefinitions-2.0.mzn`file (not sure why this is a problem, but also discussed in as a problem in the MiniZinc discussion forums)
* Adjust the ortools.msc executable path. It specifies `fz` as the executable to run which does not exist, not the existing `fzn-or-tools`
* Make sure to _not_ use the "Verbose solving" flag in the Configuration editor, as that sends the `-v` flag, which the OR-Tools flatzinc runner does not handle (although it is specified as handled in the `ortools.msc` file)

**Comment by lperron** [comment]
Known issue. Minizinc before 2.6.1 was missing some definitions for warm starts.

They were added to or-tools, then minizing 2.6.1 readded them, and now they conflict. 

It is fixed on the main branch.

**Comment by zayenz** [comment]
I checked in the main branch also and built form there, and all three issues were still present. Links below are to the main branch as of this comment.

1. Redefinitions file: https://github.com/google/or-tools/blob/5ad0feaa0c92232c33249802b647b90b99108e09/ortools/flatzinc/mznlib/redefinitions-2.0.mzn#L101
2. The wrong flatzinc binary name for the flatzinc executable: https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/cmake/flatzinc.cmake#L163
3. Indicating that `-v` is a supported flag: https://github.com/google/or-tools/blob/fa84bc05e72641dddfbb98164d81b8bc9bef6ea5/ortools/flatzinc/ortools.msc.in#L9

**Comment by lperron** [comment]
1. Just pushed back on main. The change was overwritten 11 days ago :-(
2. we will have a look
3.  is ok. I added the -v flags to the binary.

**Comment by Mizux** [comment]
should be fixed on main.

note: I tested it using https://github.com/MiniZinc/MiniZincIDE/releases/download/2.6.3/MiniZincIDE-2.6.3-bundle-linux-x86_64.tgz
