### ISSUE TITLE
Sulum interface no longer working with latest version.

### ISSUE THREAD

**Issue by manuelRiel** [google/or-tools#93]
When compiling Sulum with the latest or-tools version, I get the following error:

```
src/linear_solver/sulum_interface.cc: In member function ‘virtual operations_research::MPSolver::ResultStatus operations_research::SLMInterface::Solve(const operations_research::MPSolverParameters&)’:
src/linear_solver/sulum_interface.cc:607:9: error: ‘class operations_research::MPConstraint’ has no member named ‘set_activity’
     ct->set_activity(row_activity);
         ^
make: *** [objs/linear_solver/sulum_interface.o] Error 1
```

Is it possible that the Sulum-interface is out of sync with the headers provided in the latest sulum43 version? The file in question is probably `/src/linear_solver/sulum_interface.cc`

**Comment by lperron** [comment]
I pushed a tentative fix.
I do not have sulum installed to try it.

Can you check?

**Comment by manuelRiel** [comment]
Thanks for the quick response. Just tried the latest available version and still getting the same error.

```
g++ -fPIC -std=c++0x -fwrapv -O4 -DNDEBUG -Isrc -Iexamples -Isrc/gen -I/home/manu/ortools/or-tools/dependencies/sources/gflags-2.1.2/include -DARCH_K8 -Wno-deprecated -I/home/manu/ortools/or-tools/dependencies/install/include     -I/home/manu/ortools/sulum43/BraunDesert/header -DUSE_SLM   -DUSE_GLOP -DUSE_BOP -I../sparsehash-1.11/include -c src/linear_solver/sulum_interface.cc -o objs/linear_solver/sulum_interface.o
src/linear_solver/sulum_interface.cc: In member function ‘virtual operations_research::MPSolver::ResultStatus operations_research::SLMInterface::Solve(const operations_research::MPSolverParameters&)’:
src/linear_solver/sulum_interface.cc:607:9: error: ‘class operations_research::MPConstraint’ has no member named ‘set_activity’
     ct->set_activity(row_activity);
         ^
make: *** [objs/linear_solver/sulum_interface.o] Error 1
```

**Comment by lperron** [comment]
Please update again, I pushed the code after the mail

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2015-09-30 14:48 GMT+02:00 Manuel Riel <notifications@github.com>:

**Comment by manuelRiel** [comment]
That solved it. I just had to change `sulum10` to `sulum43` in `makefiles/Makefile.unix` to make it work from there. Should I change it everywhere and submit a PR for that? @lperron

**Comment by lperron** [comment]
No,

I have added a new flag in Makefile.local

please add
UNIX_SULUM_VERSION=43
 or
WINDOWS_SULUM_VERSION=43

in Makefile.local

You need to update from github.

Thanks


Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2015-10-01 9:23 GMT+02:00 Manuel Riel <notifications@github.com>:

**Comment by manuelRiel** [comment]
Works now great on Linux. On Mac I'm running into some new issues. I'm posting the failing command. First thought it had something to do with `makefiles/Makefile.unix` and the path being set to `-L$(UNIX_SLM_DIR)/linux64/bin/` instead of `mac64`. But still failing after that.

The latest (and probably last) Sulum release is here. Maybe you have a point for me.

https://drive.google.com/open?id=0B_Bi-aTO9UR0Mko2ZjVrVjFJM1E

```
clang++ -fPIC -std=c++11 -O4 -DNDEBUG -Isrc -Iexamples -Isrc/gen -I/Users/manu/Workspace/build-ortools/or-tools/dependencies/sources/gflags-2.1.2/include -DARCH_K8 -Wno-deprecated -I/Users/manu/Workspace/build-ortools/or-tools/dependencies/install/include -I/Users/manu/Workspace/build-ortools/or-tools/dependencies/install/include -DUSE_CBC -I/Users/manu/Workspace/build-ortools/or-tools/dependencies/install/include -DUSE_CLP   -I/Users/manu/Workspace/build-ortools/sulum43/BraunDesert/header -DUSE_SLM   -DUSE_GLOP -DUSE_BOP -I../sparsehash-1.11/include objs/glop/solve.o lib/liblinear_solver.a lib/libbop.a lib/libsat.a lib/libsplit.a lib/libalgorithms.a lib/libglop.a lib/libutil.a lib/libbase.a  /Users/manu/Workspace/build-ortools/or-tools/dependencies/install/lib/libCbcSolver.a /Users/manu/Workspace/build-ortools/or-tools/dependencies/install/lib/libCbc.a /Users/manu/Workspace/build-ortools/or-tools/dependencies/install/lib/libCgl.a /Users/manu/Workspace/build-ortools/or-tools/dependencies/install/lib/libOsi.a /Users/manu/Workspace/build-ortools/or-tools/dependencies/install/lib/libOsiCbc.a /Users/manu/Workspace/build-ortools/or-tools/dependencies/install/lib/libOsiClp.a /Users/manu/Workspace/build-ortools/or-tools/dependencies/install/lib/libClp.a /Users/manu/Workspace/build-ortools/or-tools/dependencies/install/lib/libCoinUtils.a       /Users/manu/Workspace/build-ortools/or-tools/dependencies/sources/gflags-2.1.2/lib/libgflags.a -lz /Users/manu/Workspace/build-ortools/or-tools/dependencies/install/lib/libprotobuf.a  -o bin/solve
Undefined symbols for architecture x86_64:
  "_SlmAddEmptyCons", referenced from:
      operations_research::SLMInterface::ExtractNewConstraints() in liblinear_solver.a(sulum_interface.o)
  "_SlmAddEmptyVars", referenced from:
      operations_research::SLMInterface::ExtractNewVariables() in liblinear_solver.a(sulum_interface.o)
  "_SlmClear", referenced from:
      operations_research::SLMInterface::Reset() in liblinear_solver.a(sulum_interface.o)
  "_SlmFreeEnv", referenced from:
      operations_research::SLMInterface::~SLMInterface() in liblinear_solver.a(sulum_interface.o)
  "_SlmFreeModel", referenced from:
      operations_research::SLMInterface::~SLMInterface() in liblinear_solver.a(sulum_interface.o)
  "_SlmGetANz64", referenced from:
      operations_research::SLMInterface::ExtractNewConstraints() in liblinear_solver.a(sulum_interface.o)
  "_SlmGetAVarsI", referenced from:
      operations_research::SLMInterface::ComputeScaledBasisL1Norm(int, int, double*, double*) const in liblinear_solver.a(sulum_interface.o)
  "_SlmGetBasisHead", referenced from:
      operations_research::SLMInterface::ComputeInverseScaledBasisL1Norm(int, int, double*, double*) const in liblinear_solver.a(sulum_interface.o)
  "_SlmGetCons", referenced from:
      operations_research::SLMInterface::ComputeExactConditionNumber() const in liblinear_solver.a(sulum_interface.o)
  "_SlmGetDbInfo", referenced from:
      operations_research::SLMInterface::Solve(operations_research::MPSolverParameters const&) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::best_objective_bound() const in liblinear_solver.a(sulum_interface.o)
  "_SlmGetIntInfo", referenced from:
      operations_research::SLMInterface::iterations() const in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::nodes() const in liblinear_solver.a(sulum_interface.o)
  "_SlmGetSolDualConsI", referenced from:
      operations_research::SLMInterface::Solve(operations_research::MPSolverParameters const&) in liblinear_solver.a(sulum_interface.o)
  "_SlmGetSolDualVarsI", referenced from:
      operations_research::SLMInterface::Solve(operations_research::MPSolverParameters const&) in liblinear_solver.a(sulum_interface.o)
  "_SlmGetSolKeyPrimConsI", referenced from:
      operations_research::SLMInterface::row_status(int) const in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::ComputeScaledBasisL1Norm(int, int, double*, double*) const in liblinear_solver.a(sulum_interface.o)
  "_SlmGetSolKeyPrimVarsI", referenced from:
      operations_research::SLMInterface::column_status(int) const in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::ComputeScaledBasisL1Norm(int, int, double*, double*) const in liblinear_solver.a(sulum_interface.o)
  "_SlmGetSolPrimVarsI", referenced from:
      operations_research::SLMInterface::Solve(operations_research::MPSolverParameters const&) in liblinear_solver.a(sulum_interface.o)
  "_SlmGetSolStatus", referenced from:
      operations_research::SLMInterface::Solve(operations_research::MPSolverParameters const&) in liblinear_solver.a(sulum_interface.o)
  "_SlmGetSulumVersion", referenced from:
      operations_research::SLMInterface::SolverVersion() const in liblinear_solver.a(sulum_interface.o)
  "_SlmGetTypeVarsI", referenced from:
      operations_research::SLMInterface::SetVariableInteger(int, bool) in liblinear_solver.a(sulum_interface.o)
  "_SlmGetVars", referenced from:
      operations_research::SLMInterface::ComputeExactConditionNumber() const in liblinear_solver.a(sulum_interface.o)
  "_SlmHintAMaxNz64", referenced from:
      operations_research::SLMInterface::ExtractNewConstraints() in liblinear_solver.a(sulum_interface.o)
  "_SlmInitBasisSolves", referenced from:
      operations_research::SLMInterface::ComputeInverseScaledBasisL1Norm(int, int, double*, double*) const in liblinear_solver.a(sulum_interface.o)
  "_SlmMakeEnv", referenced from:
      operations_research::SLMInterface::SLMInterface(operations_research::MPSolver*, bool) in liblinear_solver.a(sulum_interface.o)
  "_SlmMakeModel", referenced from:
      operations_research::SLMInterface::SLMInterface(operations_research::MPSolver*, bool) in liblinear_solver.a(sulum_interface.o)
  "_SlmOptimize", referenced from:
      operations_research::SLMInterface::Solve(operations_research::MPSolverParameters const&) in liblinear_solver.a(sulum_interface.o)
  "_SlmSetAConsI", referenced from:
      operations_research::SLMInterface::ClearConstraint(operations_research::MPConstraint*) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::ExtractOneConstraint(operations_research::MPConstraint*, int*, double*) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::ExtractNewConstraints() in liblinear_solver.a(sulum_interface.o)
  "_SlmSetAIJ", referenced from:
      operations_research::SLMInterface::SetCoefficient(operations_research::MPConstraint*, operations_research::MPVariable const*, double, double) in liblinear_solver.a(sulum_interface.o)
  "_SlmSetDbParam", referenced from:
      operations_research::SLMInterface::ConfigureSLMParameters(operations_research::MPSolverParameters const&) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::SetRelativeMipGap(double) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::SetPrimalTolerance(double) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::SetDualTolerance(double) in liblinear_solver.a(sulum_interface.o)
  "_SlmSetIntParam", referenced from:
      operations_research::SLMInterface::SetOptimizationDirection(bool) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::Solve(operations_research::MPSolverParameters const&) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::SetPresolveMode(int) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::SetLpAlgorithm(int) in liblinear_solver.a(sulum_interface.o)
  "_SlmSetKeyConsI", referenced from:
      operations_research::SLMInterface::SetConstraintBounds(int, double, double) in liblinear_solver.a(sulum_interface.o)
  "_SlmSetKeyVarsI", referenced from:
      operations_research::SLMInterface::SetVariableBounds(int, double, double) in liblinear_solver.a(sulum_interface.o)
  "_SlmSetLoConsI", referenced from:
      operations_research::SLMInterface::SetConstraintBounds(int, double, double) in liblinear_solver.a(sulum_interface.o)
  "_SlmSetLoVarsI", referenced from:
      operations_research::SLMInterface::SetVariableBounds(int, double, double) in liblinear_solver.a(sulum_interface.o)
  "_SlmSetLoggingCallback", referenced from:
      operations_research::SLMInterface::SLMInterface(operations_research::MPSolver*, bool) in liblinear_solver.a(sulum_interface.o)
  "_SlmSetNameConsI", referenced from:
      operations_research::SLMInterface::ExtractNewConstraints() in liblinear_solver.a(sulum_interface.o)
  "_SlmSetNameVarsI", referenced from:
      operations_research::SLMInterface::ExtractNewVariables() in liblinear_solver.a(sulum_interface.o)
  "_SlmSetObjFix", referenced from:
      operations_research::SLMInterface::ClearObjective() in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::ExtractObjective() in liblinear_solver.a(sulum_interface.o)
  "_SlmSetObjName", referenced from:
      operations_research::SLMInterface::SLMInterface(operations_research::MPSolver*, bool) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::Reset() in liblinear_solver.a(sulum_interface.o)
  "_SlmSetObjVarsI", referenced from:
      operations_research::SLMInterface::ClearObjective() in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::ExtractNewVariables() in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::ExtractObjective() in liblinear_solver.a(sulum_interface.o)
  "_SlmSetParamDefault", referenced from:
      operations_research::SLMInterface::Reset() in liblinear_solver.a(sulum_interface.o)
  "_SlmSetUpConsI", referenced from:
      operations_research::SLMInterface::SetConstraintBounds(int, double, double) in liblinear_solver.a(sulum_interface.o)
  "_SlmSetUpVarsI", referenced from:
      operations_research::SLMInterface::SetVariableBounds(int, double, double) in liblinear_solver.a(sulum_interface.o)
  "_SlmSolveFtranDense", referenced from:
      operations_research::SLMInterface::ComputeInverseScaledBasisL1Norm(int, int, double*, double*) const in liblinear_solver.a(sulum_interface.o)
  "_SlmWriteProblem", referenced from:
      operations_research::SLMInterface::SLMInterface(operations_research::MPSolver*, bool) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::~SLMInterface() in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::Reset() in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::WriteModel(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::SetOptimizationDirection(bool) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::SetVariableBounds(int, double, double) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::SetVariableInteger(int, bool) in liblinear_solver.a(sulum_interface.o)
      ...
  "_SlmWriteSolution", referenced from:
      operations_research::SLMInterface::SLMInterface(operations_research::MPSolver*, bool) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::~SLMInterface() in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::Reset() in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::WriteModel(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::SetOptimizationDirection(bool) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::SetVariableBounds(int, double, double) in liblinear_solver.a(sulum_interface.o)
      operations_research::SLMInterface::SetVariableInteger(int, bool) in liblinear_solver.a(sulum_interface.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/solve] Error 1
```

**Comment by manuelRiel** [comment]
Copied some of the sulum-specific settings from Linux to Mac in the Makefile and that fixed it. Will add a PR shortly.
