### ISSUE TITLE
CP-SAT: Best way to find infeasible constraints

### ISSUE THREAD

**Issue by Phibedy** [google/or-tools#973]
Is there some builtin method to get the constraints which can't be solved?

If not would it be better to try
 * to solve it ignoring one element after the other (permutations or maybe some smart search)
 * make all constraints optionally by introducing a boolean variable which states if the constraint should hold. Afterwards the sum of all booleans is maximized

Thank you for your time :+1:

**Comment by lperron** [comment]
which solver?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Phibedy** [comment]
Sorry missed that, cp-sat

**Comment by lperron** [comment]
A sad answer as the SAT solver knows more, but the code is not yet written.

1) Yes, you can do better than 1 constraint at a time.  See QuickXPlain https://pdfs.semanticscholar.org/dee6/53e324b42311f93adf83611a985028f8b54c.pdf
2) Not all constraints supports enforcement literals, mostly boolean constraints (except xor), and linear one + interval variables. So option 2 may not be feasible.

If feasible, I would use option 2, but not all constraints accept enforcement literals.

**Comment by eblume** [comment]
Regarding option 2, specifically XOr,

can't you just enforce XOr like such?

`model.Add(sum(boolean_constraints) == 1).OnlyEnforceIf(enforcement_literal)`

I was curious as to why XOr wasn't allowed to have an enforcement literal, and have used the above successfully.

------

Regarding the topic of finding infeasible constraints: is there any update on adding this feature to CP-SAT, and can I help? This would be a very large help to me, as currently I am working around it by re-running the problem with manual relaxations, and it's getting complicated very fast.

Thank you very much!

**Comment by lperron** [comment]
xor works on an array.
For 2 booleans, this is easy.
For n booleans, the definition is sum is odd, which has a specialized
propagator, that does not yet support enforcement literals.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le sam. 20 avr. 2019 à 22:32, Erich Blume <notifications@github.com> a
écrit :

**Comment by eblume** [comment]
Thank you for the real-time response! I wasn't aware that xor on an array was considered sum-mod-2 in boolean algebra. For the concept of "One and only one of these LinearExpressions MUST be true", is my formulation (`sum(...) == 1`) sufficient? It appears to work, although perhaps that is what is causing my unexpected 'INFEASIBLE' problem.

**Comment by lperron** [comment]
It is valid only if n = 2

Otherwise, create an extra integer variable, and add sum(n) - 2 * extra_var
== 1.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le sam. 20 avr. 2019 à 22:39, Erich Blume <notifications@github.com> a
écrit :

**Comment by joegaudet** [comment]
Hey Guys,

Also wondering if there is anyway to determine which constraint is causing infeasibility, simply to report it back to the user.

**Comment by lalithsuresh** [comment]
@joegaudet not yet: https://github.com/google/or-tools/issues/1565

Not sure if it's on their roadmap.

**Comment by lperron** [comment]
Not yet. We have too much to do in the performance of the solver before
that.

Le mar. 10 sept. 2019 à 18:06, Lalith Suresh <notifications@github.com> a
écrit :

**Comment by trianta2** [comment]
I too would find this feature very useful

**Comment by ykzeng** [comment]
I second @trianta2 , many times the constraints are built on the fly based on real-world parameters which may not be feasible, so it would be nice to be able to identify those constraints that is preventing the optimization

**Comment by joegaudet** [comment]
@Mizux curious if there's any timeline on this, I see that it's been added to the TODO file. This tool is great, however it's very challenging to identify the source of issues with infeasibility.

**Comment by javiermas** [comment]
Same here. It's really a pain to debug problems with the model. Particularly when you're using it with a myriad of input data. This has been our biggest problem by far with the ortools library.

**Comment by joegaudet** [comment]
We end up having to use heuristics to try and determine which input is
likely the issue.

**Comment by joegaudet** [comment]
@Mizux noticed you moved this in Feature Requests, curious if there's any sort of timeline on it? Quarters? Years?

Certainly appreciate all of the work people have done putting this together, just trying to plan what we might be able to do to address failing constraints on our system.

**Comment by lperron** [comment]
In the general sense, give a model, find why it is infeasible, probably
never. I do not believe this is the right approach.
I understand it is needed to find a stupidly wrong constraint (bad data),
but in the general case, the result is unusable.

What you can do is instrument your code with enforcement literals. This
part is a bit tricky only linear constraints, Boolean constraints, and
intervals support enforcement literals. But in the end, you want to achieve:

literal1 => one part of the model
literal2 => another part of the model.

Then you want a minimal number of false literal to get a feasible model.

You can do either by minimizing the (weighted) sum of literals, or adding
them as assumptions in the model.
Then the solver will try to heuristically find a (local) minimum assignment
of false literals to get a feasible model.

Both are already available, but I did not have the time to document it.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mar. 27 oct. 2020 à 23:35, Joe Gaudet <notifications@github.com> a
écrit :

**Comment by joegaudet** [comment]
I'm not sure I follow, if I have a variety of inequalities in my model,
from the summing of assignment Booleans. How can I tell that one cannot be
satisfied in the presence of another inequality?

Is there an example of using enforcement literals in python?

**Comment by lperron** [comment]
Each inequality has an enforcement literal.
Then you maximize the sum of enforcement literals.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 28 oct. 2020 à 01:55, Joe Gaudet <notifications@github.com> a
écrit :

**Comment by joegaudet** [comment]
But if the constraints themselves are _requirements_ which is to say if
they cannot be solved the model cannot be solver. I'm not sure I understand
how maximizing them would help?

Could you give a pseudo-code example?

.joe

**Comment by lalithsuresh** [comment]
@joegaudet what Laurent means is to re-run the model but with all the constraints having an enforcement literal attached (so you'll have to modify your code or have a way to conditionally attach these literals in your code). You then have to add a new objective function which maximizes the sum of these enforcement literals. Once a solution is found, the literals that are false point to the "infeasible constraints".

This should work as long as your constraints support enforcement literals, but not all do, which is the drawback (e.g., cumulative and other scheduling constraints).

**Comment by joegaudet** [comment]
Ahhhh gotcha. Is there an example of these literals in python somewhere? I currently re run a setup manually when some constraints are fungible.

**Comment by lperron** [comment]
Yes. But scheduling uses intervals that support enforcement literals. The
circuit constraint supports bon visited nodes

So this is tedious, but should be feasible.

Le mer. 28 oct. 2020 à 20:56, Lalith Suresh <notifications@github.com> a
écrit :

**Comment by lalithsuresh** [comment]
@lperron One question though. You mentioned earlier in thread that the solver "knows more". My understanding was that the CP-SAT solver computes cores as part of the search process, but is the problem that these cores are hard to meaningfully relate back into vars/constraints in the input model?

**Comment by lperron** [comment]
The problem with explanation is that they are hard to process.
You will get a lot of constraints, including all the trivial consistency
constraints of the model.

To be useful, explanations need to be targeted. In practise, you decompose
the model into a background model and an active model.

To use the cores, you need to fill this field in the model proto:

  // A list of literals. The model will be solved assuming all these
literals
  // are true. Compared to just fixing the domain of these literals, using
this
  // mechanism is slower but allows in case the model is INFEASIBLE to get a
  // potentially small subset of them that can be used to explain the
  // infeasibility.
  //
  // Think (IIS), except when you are only concerned by the provided
  // assumptions. This is powerful as it allows to group a set of logically
  // related constraint under only one enforcement literal which can
potentially
  // give you a good and interpretable explanation for infeasibility.
  //
  // Such infeasibility explanation will be available in the
  // sufficient_assumptions_for_infeasibility response field.
  repeated int32 assumptions = 7;

This replaces the sum(literals) objective. It will be much faster, but the
resulting explanation will not be proven minimal, just a heuristic result.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le mer. 28 oct. 2020 à 21:06, Lalith Suresh <notifications@github.com> a
écrit :

**Comment by lalithsuresh** [comment]
Thanks @lperron! This is quite the hidden gem. :) I just gave it a spin and think this would be quite useful already. 

For everyone else, here's an example in Java.

```
    @Test
    public void assumptionsTest() {
        // Create the model.
        final CpModel model = new CpModel();
        final IntVar v1 = model.newBoolVar("c1");
        final IntVar v2 = model.newBoolVar("c2");
        final IntVar i1 = model.newIntVar(0, 5, "c1");
        final IntVar i2 = model.newIntVar(0, 5, "c1");

        model.addGreaterOrEqual(LinearExpr.sum(new IntVar[]{i1, i2}), 11).onlyEnforceIf(v1);
        model.addLessOrEqual(LinearExpr.sum(new IntVar[]{i1, i2}), 5).onlyEnforceIf(v2);
        model.getBuilder().addAssumptions(v1.getIndex());
        model.getBuilder().addAssumptions(v2.getIndex());

        final CpSolver solver = new CpSolver();
        solver.getParameters().setCpModelPresolve(false);
        solver.getParameters().setLogSearchProgress(true);
        final CpSolverStatus status = solver.solve(model);

        assertEquals(CpSolverStatus.INFEASIBLE, status);
        for (final int varIndex: solver.response().getSufficientAssumptionsForInfeasibilityList()) {
            System.out.println(model.getBuilder().getVariables(varIndex)); // correctly prints variable "c1"
        }
    }

```

**Comment by ChristopherHamkins** [comment]
Laurent Perron gave me a tip in an answer to a different question about how to simulate the enforcement literals for constraints that don't have them "out of the box": make a second set of variables to which the constraint is applied (always), and enforce their equality to the original variables. The equality constraint can use its enforcement literal, and the end effect is the same (well logically but perhaps not in performance).

**Comment by tias** [comment]
This is great!

It was a bit tricky initially, but here is the corresponding Python example:

```python
# need version 8.0 or higher, or definitly not 7.3
from ortools.sat.python import cp_model

if True:
    # Creates the model.
    model = cp_model.CpModel()

    # Creates the variables.
    v0 = model.NewBoolVar("buggyVarIndexToVarProto")
    # model.VarIndexToVarProto(0) always returns the last created variable...?
    v1 = model.NewBoolVar("v1")
    v2 = model.NewBoolVar("v2")
        
    i1 = model.NewIntVar(0, 5, "i1")
    i2 = model.NewIntVar(0, 5, "i2")
        
    # Creates the constraints.
    model.Add(i1+i2 >= 11).OnlyEnforceIf(v1) # can't be satisfied
    model.Add(i1+i2 <= 5).OnlyEnforceIf(v2)
    
    # define assumption literals
    model.Proto().assumptions.append(v1.Index())
    model.Proto().assumptions.append(v2.Index())
    
    # Creates a solver and solves the model.
    solver = cp_model.CpSolver()
    status = solver.Solve(model)
        
    assert status == cp_model.INFEASIBLE
    for var_index in solver.ResponseProto().sufficient_assumptions_for_infeasibility:
        print(var_index, model.VarIndexToVarProto(var_index)) # prints "v1"
```

I think there is a bug in VarIndexToVarProto() which I'll report separately, which requires the 'v0' to be added.

Thanks to everybody in this thread for exposing this exists.


+1 for adding a pass-through `model.AddAssumptions()` and `solver.GetSufficientAssumptionsForInfeasibility()` to the Python interface, so this functionalty can become more known!


Kind regards,
Tias

**Comment by lperron** [comment]
I fixed the VarIndexToVarProto bug (which as only wrong when the index was
0).
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00

**Comment by stradivari96** [comment]
@tias just in case you missed it, this example was introduced in 8.2:
https://github.com/google/or-tools/blob/master/ortools/sat/samples/assumptions_sample_sat.py

**Comment by PeterAaser** [comment]
Is there a chance to get a C++ version of this trick? The APIs are very divergent, I've been unable to recreate it

**Comment by lperron** [comment]
https://github.com/google/or-tools/blob/master/ortools/sat/samples/assumptions_sample_sat.cc

Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le lun. 12 avr. 2021 à 11:11, Peter Aaser ***@***.***> a
écrit :

**Comment by PeterAaser** [comment]
Wow, that was fast, thanks!

**Comment by eliyahumasinter** [comment]
Something that I did not see any proper documentation on, which hopefully will be useful to others is that if you set a maximize/minimize objective in the cp sat solver, the sufficient assumptions for infeasibility function will return all assumptions (`solver.ResponseProto().sufficient_assumptions_for_infeasibility`). In order to get the minimal set of infeasible constraints, you first should solve without a maximization objective and only afterward enable the objective and continue solving the updated model.

**Comment by NaifAlqahtani** [comment]
> you first should solve without a maximization objective and only afterward enable the objective and continue solving the updated model.

Can you please elaborate on that? How would that look like in code? @eliyahumasinter

**Comment by eliyahumasinter** [comment]
@NaifAlqahtani 
We first check to see if the model is feasible. The constraint assigned to v1 is not possible to be met. We only enforce v1 if a1 is true (which we set as an assumption). We expect solver.SufficientAssumptionsForInfeasibility() to return just a1 since a2 and a3 are not problematic. However, if you were to set the maximization objective before solving, you would get a1, a2, and a3 as the minimal infeasible set. Obviously, just a1 is problematic which is revealed by solving the model twice: first to ensure feasibility, and only after to maximize.

```python
from ortools.sat.python import cp_model
model = cp_model.CpModel()

x = model.NewIntVar(0,10, 'x')
y = model.NewIntVar(0,10, 'y')
z = model.NewIntVar(0,10, 'z')

a1 = model.NewBoolVar('a1')
a2 = model.NewBoolVar('a2')
a3 = model.NewBoolVar('a3')

v1 = model.Add(x==11).OnlyEnforceIf(a1) #not possible because of x's bound
v2 = model.Add(x>5).OnlyEnforceIf(a2)
v3 = model.Add(x>6).OnlyEnforceIf(a3)

vars = [a1,a2,a3]
model.AddAssumptions(vars)

#this is the variable we will maximaize.
solver = cp_model.CpSolver()
#If we were to set a maximization objective here, we would receive a1, a2, and a3 as the minimal set
status = solver.Solve(model)

if status == cp_model.OPTIMAL or status == cp_model.FEASIBLE:
    print(f"Maximum of objective function: {solver.ObjectiveValue()}\n")
    print(f"x = {solver.Value(x)}")
    print(f"y = {solver.Value(y)}")
    #Only maximize once we know that the model is solvable 
    model.Maximize(z) #some maximization or minimization
    status = solver.Solve(model)


else:
    print("No solution found. Minimal infeasible conditions: ")
    #We haven't set any maximization objective yet so we can get the minimal result
    for i in solver.SufficientAssumptionsForInfeasibility():
        print(model.VarIndexToVarProto(i).name)

```

**Comment by NaifAlqahtani** [comment]
Thanks for your response @eliyahumasinter 

How would this be accomplished if I wanted to use OnlyEnforceIf on a constraint already?

Take for example this channeling code from the docs. How would I add assumptions to the constraint using the `b` boolean variable: 
```python
    # Create the CP-SAT model.
    model = cp_model.CpModel()

    # Declare our two primary variables.
    x = model.NewIntVar(0, 10, "x")
    y = model.NewIntVar(0, 10, "y")

    # Declare our intermediate boolean variable.
    b = model.NewBoolVar("b")

    # Implement b == (x >= 5).
    model.Add(x >= 5).OnlyEnforceIf(b)
    model.Add(x < 5).OnlyEnforceIf(b.Not())

    # Create our two half-reified constraints.
    # First, b implies (y == 10 - x).
    model.Add(y == 10 - x).OnlyEnforceIf(b)
    # Second, not(b) implies y == 0.
    model.Add(y == 0).OnlyEnforceIf(b.Not())
``` 

How would I do `model.Add(x >= 5).OnlyEnforceIf(b)` with an assumption? 
Essentially achieving an idea similar to: `model.Add(x >= 5).OnlyEnforceIf(b).OnlyEnforceIf(v1)` where `v1` is the assumption var.

**Comment by cjwatterson** [comment]
> Essentially achieving an idea similar to: `model.Add(x >= 5).OnlyEnforceIf(b).OnlyEnforceIf(v1)` where `v1` is the assumption var.

You can use `model.Add(x >= 5).OnlyEnforceIf({b, v1})`. That's AND for OR you need another intermediate boolean.
